// packages/vps/src/templates/scaffold/trees/next/app/page.tsx
export default function Page() {
  return (
    <main className="min-h-screen flex items-center justify-center px-6 py-12">
      <div className="flex flex-col items-center gap-8 text-center max-w-xl w-full">
        <div className="text-xs uppercase tracking-[0.2em] opacity-50">ellul</div>
        <div>
          <h1 className="text-5xl font-semibold tracking-tight">Your app is ready.</h1>
          <p className="text-base opacity-60 leading-relaxed">Ask the agent to build, or edit this page to start shipping.</p>
        </div>
        <div className="grid grid-cols-2 gap-3 w-full text-sm text-left mt-4">
          <div className="rounded-lg border border-current/10 p-4">
            <div className="font-medium mb-1">Edit</div>
            <div className="opacity-60 text-xs">Change this file, see it live.</div>
          </div>
          <div className="rounded-lg border border-current/10 p-4">
            <div className="font-medium mb-1">Chat</div>
            <div className="opacity-60 text-xs">Ask the agent to build features.</div>
          </div>
        </div>
      </div>
    </main>
  );
}

// packages/vps/src/templates/scaffold/trees/nuxt/app/app.vue
<template>
  <main class="min-h-screen flex items-center justify-center px-6 py-12">
    <div class="flex flex-col items-center gap-8 text-center max-w-xl w-full">
      <div class="text-xs uppercase tracking-[0.2em] opacity-50">ellul</div>
      <div>
        <h1 class="text-5xl font-semibold tracking-tight">Your app is ready.</h1>
        <p class="text-base opacity-60 leading-relaxed">Ask the agent to build, or edit this page to start shipping.</p>
      </div>
      <div class="grid grid-cols-2 gap-3 w-full text-sm text-left mt-4">
        <div class="rounded-lg border border-current/10 p-4">
          <div class="font-medium mb-1">Edit</div>
          <div class="opacity-60 text-xs">Change this file, see it live.</div>
        </div>
        <div class="rounded-lg border border-current/10 p-4">
          <div class="font-medium mb-1">Chat</div>
          <div class="opacity-60 text-xs">Ask the agent to build features.</div>
        </div>
      </div>
    </div>
  </main>
</template>
